### PR TITLE
Implemented a cURL Interceptor for Enhanced Request Debugging

### PR DESCRIPTION
**Pull request by gilbertohnrq**
**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [x] Feature
- [ ] Documentation
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch (or `v[X]` branch)
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/bageldb/docs)  or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to [start a new feature discussion](https://github.com/bageldb/libraries/discussions/new?category=ideas-proposals) first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by gilbertohnrq** [comment]
This enhancement is necessary as it substantially improves the debugging process for network requests within the application. By implementing a cURL Logging Interceptor, we enable a detailed logging of all outgoing HTTP requests. This not only assists developers in tracking and identifying potential issues with the API calls but also helps in understanding the flow and timing of data throughout the application.

Adding this feature can significantly reduce time spent on diagnosing and fixing network related bugs, which in turn, increases the overall efficiency of the development process. Additionally, this can serve as a valuable tool for new developers onboarding onto the project, helping them understand the structure and sequence of network requests being made in the application.

**Comment by nallon** [comment]
Apologies for the delay in my response.

I agree that adding a cURL Logging Interceptor would enhance our debugging process, aid in tracking API call issues, and be beneficial for new developers. This improvement seems valuable for our overall development efficiency.

Looking forward to reviewing the updated code.

**Comment by nallon** [comment]
@gilbertohnrq 
I took your implementation and integrated it into the latest version of the library.
Thank you again

**Comment by nallon** [comment]
@gilbertohnrq
I took your implementation and integrated it into the latest version of the library.
Thank you for the contibution

**Pull request closed without merging**
